name: itunes_media
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.2.3
  url_launcher: ^6.3.0
  just_audio: ^0.9.37
  flutter_svg: ^2.0.10+1
  http_certificate_pinning: ^2.1.3
  flutter_jailbreak_detection: ^1.10.0
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/certificate/
    - assets/images/
